# Generated by Django 2.1.1 on 2018-10-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='annotator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.CharField(max_length=20)),
                ('classifier', models.CharField(max_length=20)),
                ('approver', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=200)),
                ('classifierData', models.TextField()),
                ('approverData', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
