# Generated by Django 2.1.1 on 2018-10-08 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_intermidiate'),
    ]

    operations = [
        migrations.CreateModel(
            name='processed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeId', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=30)),
                ('approverName', models.CharField(max_length=30)),
                ('resume', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='intermidiate',
            name='userName',
            field=models.CharField(max_length=30),
            preserve_default=False,
        ),
    ]
