# Generated by Django 2.1.1 on 2018-10-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0005_auto_20181008_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_annotated_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeId', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=30)),
                ('annotaedData', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='annotator',
        ),
        migrations.AlterField(
            model_name='intermidiate',
            name='resumeId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='processed',
            name='resumeId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='resumeId',
            field=models.CharField(max_length=50),
        ),
    ]
