# Generated by Django 2.1.1 on 2018-10-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0006_auto_20181008_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_annotated_data',
            name='tagName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
