# Generated by Django 2.1.1 on 2018-10-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0007_temp_annotated_data_tagname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_annotated_data',
            name='tagName',
        ),
        migrations.AddField(
            model_name='temp_annotated_data',
            name='tagId',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
