# Generated by Django 2.1.1 on 2018-10-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0008_auto_20181009_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermidiate',
            name='tempUserId',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processed',
            name='status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='tempUserId',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intermidiate',
            name='resumeId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='intermidiate',
            name='userName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='processed',
            name='approverName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='processed',
            name='resumeId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='processed',
            name='userName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='resumeId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='temp_annotated_data',
            name='annotaedData',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='temp_annotated_data',
            name='resumeId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='temp_annotated_data',
            name='tagId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='temp_annotated_data',
            name='userName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='loginKey',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=255),
        ),
    ]
