# Generated by Django 2.1.1 on 2018-10-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0009_auto_20181012_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='systemName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
