# Generated by Django 2.1.1 on 2018-10-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0010_user_systemname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='systemName',
        ),
    ]
